package seeders

import (
	"keerja-backend/internal/domain/company"
	"log"

	"github.com/google/uuid"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
)

// CompaniesSeeder seeds sample companies for development/testing
func CompaniesSeeder(db *gorm.DB) error {
	log.Println("Seeding sample companies...")

	// Helper function to create string pointer
	strPtr := func(s string) *string { return &s }

	companies := []company.Company{
		{
			UUID:         uuid.New(),
			CompanyName:  "Gojek Indonesia",
			Slug:         "gojek-indonesia",
			LegalName:    strPtr("PT Aplikasi Karya Anak Bangsa"),
			Industry:     strPtr("Technology"),
			CompanyType:  strPtr("startup"),
			SizeCategory: strPtr("1000+"),
			WebsiteURL:   strPtr("https://www.gojek.com"),
			EmailDomain:  strPtr("gojek.com"),
			Phone:        strPtr("+62-21-50884200"),
			City:         strPtr("Jakarta"),
			Province:     strPtr("DKI Jakarta"),
			Country:      "Indonesia",
			About:        strPtr("Super app providing on-demand services including ride-hailing, food delivery, logistics, and payments."),
			Verified:     true,
			IsActive:     true,
		},
		{
			UUID:         uuid.New(),
			CompanyName:  "Tokopedia",
			Slug:         "tokopedia",
			LegalName:    strPtr("PT Tokopedia"),
			Industry:     strPtr("E-Commerce"),
			CompanyType:  strPtr("startup"),
			SizeCategory: strPtr("1000+"),
			WebsiteURL:   strPtr("https://www.tokopedia.com"),
			EmailDomain:  strPtr("tokopedia.com"),
			City:         strPtr("Jakarta"),
			Province:     strPtr("DKI Jakarta"),
			Country:      "Indonesia",
			About:        strPtr("Indonesia's leading e-commerce platform connecting millions of buyers and sellers."),
			Verified:     true,
			IsActive:     true,
		},
		{
			UUID:         uuid.New(),
			CompanyName:  "Bukalapak",
			Slug:         "bukalapak",
			LegalName:    strPtr("PT Bukalapak.com Tbk"),
			Industry:     strPtr("E-Commerce"),
			CompanyType:  strPtr("public"),
			SizeCategory: strPtr("1000+"),
			WebsiteURL:   strPtr("https://www.bukalapak.com"),
			EmailDomain:  strPtr("bukalapak.com"),
			City:         strPtr("Jakarta"),
			Province:     strPtr("DKI Jakarta"),
			Country:      "Indonesia",
			About:        strPtr("Indonesian e-commerce company empowering small and medium enterprises."),
			Verified:     true,
			IsActive:     true,
		},
		{
			UUID:         uuid.New(),
			CompanyName:  "Traveloka",
			Slug:         "traveloka",
			LegalName:    strPtr("PT Trinusa Travelindo"),
			Industry:     strPtr("Travel & Tourism"),
			CompanyType:  strPtr("startup"),
			SizeCategory: strPtr("1000+"),
			WebsiteURL:   strPtr("https://www.traveloka.com"),
			EmailDomain:  strPtr("traveloka.com"),
			City:         strPtr("Jakarta"),
			Province:     strPtr("DKI Jakarta"),
			Country:      "Indonesia",
			About:        strPtr("Southeast Asia's leading travel platform for booking flights, hotels, and activities."),
			Verified:     true,
			IsActive:     true,
		},
		{
			UUID:         uuid.New(),
			CompanyName:  "Shopee Indonesia",
			Slug:         "shopee-indonesia",
			LegalName:    strPtr("PT Shopee International Indonesia"),
			Industry:     strPtr("E-Commerce"),
			CompanyType:  strPtr("private"),
			SizeCategory: strPtr("1000+"),
			WebsiteURL:   strPtr("https://www.shopee.co.id"),
			EmailDomain:  strPtr("shopee.com"),
			City:         strPtr("Jakarta"),
			Province:     strPtr("DKI Jakarta"),
			Country:      "Indonesia",
			About:        strPtr("Leading mobile-first marketplace in Southeast Asia and Taiwan."),
			Verified:     true,
			IsActive:     true,
		},
		{
			UUID:         uuid.New(),
			CompanyName:  "Grab Indonesia",
			Slug:         "grab-indonesia",
			LegalName:    strPtr("PT Solusi Transportasi Indonesia"),
			Industry:     strPtr("Technology"),
			CompanyType:  strPtr("startup"),
			SizeCategory: strPtr("1000+"),
			WebsiteURL:   strPtr("https://www.grab.com"),
			EmailDomain:  strPtr("grab.com"),
			City:         strPtr("Jakarta"),
			Province:     strPtr("DKI Jakarta"),
			Country:      "Indonesia",
			About:        strPtr("Southeast Asia's leading superapp offering transport, food delivery, and financial services."),
			Verified:     true,
			IsActive:     true,
		},
		{
			UUID:         uuid.New(),
			CompanyName:  "Ruangguru",
			Slug:         "ruangguru",
			LegalName:    strPtr("PT Ruang Raya Indonesia"),
			Industry:     strPtr("Education Technology"),
			CompanyType:  strPtr("startup"),
			SizeCategory: strPtr("201-1000"),
			WebsiteURL:   strPtr("https://www.ruangguru.com"),
			EmailDomain:  strPtr("ruangguru.com"),
			City:         strPtr("Jakarta"),
			Province:     strPtr("DKI Jakarta"),
			Country:      "Indonesia",
			About:        strPtr("Indonesia's largest online learning platform providing educational content and tutoring services."),
			Verified:     true,
			IsActive:     true,
		},
		{
			UUID:         uuid.New(),
			CompanyName:  "Bank Mandiri",
			Slug:         "bank-mandiri",
			LegalName:    strPtr("PT Bank Mandiri (Persero) Tbk"),
			Industry:     strPtr("Banking & Finance"),
			CompanyType:  strPtr("public"),
			SizeCategory: strPtr("1000+"),
			WebsiteURL:   strPtr("https://www.bankmandiri.co.id"),
			EmailDomain:  strPtr("bankmandiri.co.id"),
			City:         strPtr("Jakarta"),
			Province:     strPtr("DKI Jakarta"),
			Country:      "Indonesia",
			About:        strPtr("Indonesia's largest bank by assets, providing comprehensive banking services."),
			Verified:     true,
			IsActive:     true,
		},
		{
			UUID:         uuid.New(),
			CompanyName:  "Telkom Indonesia",
			Slug:         "telkom-indonesia",
			LegalName:    strPtr("PT Telekomunikasi Indonesia (Persero) Tbk"),
			Industry:     strPtr("Telecommunications"),
			CompanyType:  strPtr("public"),
			SizeCategory: strPtr("1000+"),
			WebsiteURL:   strPtr("https://www.telkom.co.id"),
			EmailDomain:  strPtr("telkom.co.id"),
			City:         strPtr("Bandung"),
			Province:     strPtr("Jawa Barat"),
			Country:      "Indonesia",
			About:        strPtr("State-owned telecommunications and network provider in Indonesia."),
			Verified:     true,
			IsActive:     true,
		},
		{
			UUID:         uuid.New(),
			CompanyName:  "OVO",
			Slug:         "ovo",
			LegalName:    strPtr("PT Visionet Internasional"),
			Industry:     strPtr("Financial Technology"),
			CompanyType:  strPtr("startup"),
			SizeCategory: strPtr("201-1000"),
			WebsiteURL:   strPtr("https://www.ovo.id"),
			EmailDomain:  strPtr("ovo.id"),
			City:         strPtr("Jakarta"),
			Province:     strPtr("DKI Jakarta"),
			Country:      "Indonesia",
			About:        strPtr("Leading Indonesian fintech company providing digital payment and financial services."),
			Verified:     true,
			IsActive:     true,
		},
		{
			UUID:         uuid.New(),
			CompanyName:  "Blibli",
			Slug:         "blibli",
			LegalName:    strPtr("PT Global Digital Niaga Tbk"),
			Industry:     strPtr("E-Commerce"),
			CompanyType:  strPtr("public"),
			SizeCategory: strPtr("1000+"),
			WebsiteURL:   strPtr("https://www.blibli.com"),
			EmailDomain:  strPtr("blibli.com"),
			City:         strPtr("Jakarta"),
			Province:     strPtr("DKI Jakarta"),
			Country:      "Indonesia",
			About:        strPtr("Omnichannel platform offering a wide range of products and services."),
			Verified:     true,
			IsActive:     true,
		},
		{
			UUID:         uuid.New(),
			CompanyName:  "Xendit",
			Slug:         "xendit",
			LegalName:    strPtr("PT Xendit Teknologi Indonesia"),
			Industry:     strPtr("Financial Technology"),
			CompanyType:  strPtr("startup"),
			SizeCategory: strPtr("201-1000"),
			WebsiteURL:   strPtr("https://www.xendit.co"),
			EmailDomain:  strPtr("xendit.co"),
			City:         strPtr("Jakarta"),
			Province:     strPtr("DKI Jakarta"),
			Country:      "Indonesia",
			About:        strPtr("Payment gateway infrastructure for Southeast Asia, helping businesses accept payments."),
			Verified:     true,
			IsActive:     true,
		},
		{
			UUID:         uuid.New(),
			CompanyName:  "Tiket.com",
			Slug:         "tiket-com",
			LegalName:    strPtr("PT Global Tiket Network"),
			Industry:     strPtr("Travel & Tourism"),
			CompanyType:  strPtr("private"),
			SizeCategory: strPtr("201-1000"),
			WebsiteURL:   strPtr("https://www.tiket.com"),
			EmailDomain:  strPtr("tiket.com"),
			City:         strPtr("Jakarta"),
			Province:     strPtr("DKI Jakarta"),
			Country:      "Indonesia",
			About:        strPtr("Online travel booking platform for flights, hotels, trains, and attractions."),
			Verified:     true,
			IsActive:     true,
		},
		{
			UUID:         uuid.New(),
			CompanyName:  "Halodoc",
			Slug:         "halodoc",
			LegalName:    strPtr("PT Media Dokter Investama"),
			Industry:     strPtr("Healthcare Technology"),
			CompanyType:  strPtr("startup"),
			SizeCategory: strPtr("201-1000"),
			WebsiteURL:   strPtr("https://www.halodoc.com"),
			EmailDomain:  strPtr("halodoc.com"),
			City:         strPtr("Jakarta"),
			Province:     strPtr("DKI Jakarta"),
			Country:      "Indonesia",
			About:        strPtr("Indonesia's leading healthtech platform connecting patients with doctors and pharmacies."),
			Verified:     true,
			IsActive:     true,
		},
		{
			UUID:         uuid.New(),
			CompanyName:  "Sayurbox",
			Slug:         "sayurbox",
			LegalName:    strPtr("PT Sayurbox Indonesia"),
			Industry:     strPtr("E-Commerce"),
			CompanyType:  strPtr("startup"),
			SizeCategory: strPtr("51-200"),
			WebsiteURL:   strPtr("https://www.sayurbox.com"),
			EmailDomain:  strPtr("sayurbox.com"),
			City:         strPtr("Jakarta"),
			Province:     strPtr("DKI Jakarta"),
			Country:      "Indonesia",
			About:        strPtr("Online grocery platform delivering fresh produce directly from farmers."),
			Verified:     true,
			IsActive:     true,
		},
	}

	// Use OnConflict to update existing companies or create new ones
	result := db.Clauses(clause.OnConflict{
		Columns:   []clause.Column{{Name: "slug"}},
		DoUpdates: clause.AssignmentColumns([]string{"company_name", "industry", "company_type", "size_category", "website_url", "city", "province", "about", "is_active", "updated_at"}),
	}).Create(&companies)

	if result.Error != nil {
		log.Printf("Failed to seed companies: %v", result.Error)
		return result.Error
	}

	log.Printf("Successfully seeded %d companies", len(companies))
	return nil
}
