run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - unconvert
    - bodyclose
    - dupl
    - errorlint
    - goconst
    - gocritic
    - gosec
    - nakedret
    - nolintlint
    - prealloc
    - revive
    - rowserrcheck
    - sqlclosecheck
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
  
  govet:
    enable-all: true
    disable:
      - fieldalignment
  
  goconst:
    min-len: 3
    min-occurrences: 3

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style

  dupl:
    threshold: 150

issues:
  exclude-dirs:
    - tests
    - mocks
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
        - errcheck

    - path: mocks/
      linters:
        - dupl
        - gosec

  max-issues-per-linter: 0
  max-same-issues: 0
